name: Deploy to Vercel with Fault-Finding
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --no-frozen-lockfile
        continue-on-error: false  # Stops on install fails
      - name: Build
        run: pnpm build
        continue-on-error: false  # Logs full TS/build errors
      - name: Lint
        run: pnpm lint  # Or tsc --noEmit for TS check
        continue-on-error: false
      - name: Deploy to Vercel
        uses: vercel/action@v1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Deploy Failed: ${{ github.run_id }}',
              body: 'Check logs: \( {{ github.server_url }}/ \){{ github.repository }}/actions/runs/${{ github.run_id }}'
            });